---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    pgp: >-
      F5D640651C80454BD2949922F434D770F325B04C
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    pgp: >-
      E931188151B90EF6EF84FBCFADD768BB9422F11B,
      F5D640651C80454BD2949922F434D770F325B04C
