---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: jellyfin
      version: 9.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/k8s-at-home/jellyfin
      tag: v10.7.7
    env:
      TZ: "Asia/Shanghai"
      JELLYFIN_CACHE_DIR: "/config/cache"
    podSecurityContext:
      supplementalGroups:
        - 44
        - 107
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    service:
      main:
        type: LoadBalancer
        externalIPs:
          - "${SVC_JELLYFIN_ADDR}"
        externalTrafficPolicy: Local
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "jellyfin.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "jellyfin.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: jellyfin-config-v1
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NAS_ADDR}"
            path: /tank/Media
        mountPath: /media
        readOnly: true
      transcode:
        enabled: true
        type: emptyDir
        medium: Memory
    podAnnotations:
      backup.velero.io/backup-volumes: config
    resources:
      limits:
        gpu.intel.com/i915: 1
