---
- hosts:
    - master
    - worker
  become: true
  gather_facts: true
  any_errors_fatal: true
  tasks:
    - name: upgrade
      ansible.builtin.pacman:
        upgrade: yes
        update_cache: yes
      register: pacman_upgrade
      retries: 5
      until: pacman_upgrade is success
