---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wireguard
  namespace: wireguard
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: wireguard
      version: 1.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/k8s-at-home/wireguard
      tag: v1.0.20210914
    env:
      TZ: "Asia/Shanghai"
    service:
      main:
        ports:
          vpn:
            enabled: true
            port: 24653
            protocol: UDP
      wg:
        enabled: true
        type: LoadBalancer
        externalIPs:
          - "${SVC_WIREGUARD_ADDR}"
        externalTrafficPolicy: Local
        ports:
          wg:
            enabled: true
            port: 24653
            protocol: UDP
            targetPort: 24653
    configSecret:
      enabled: true
      config: |
        W0ludGVyZmFjZV0KUHJpdmF0ZUtleSA9IG1FeEtPWnZhUHZQWFhiVzVjdUV3WE9EVmMzMFZZcXJWNmZUcGZQd1g0WDQ9CkFkZHJlc3MgPSAxOTIuMTY4LjUxLjEvMjQKTGlzdGVuUG9ydCA9IDI0NjUzCgpbUGVlcl0KUHVibGljS2V5ID0gNk83QlA4WHA0aTl2c2owdjhKZC9pRkZTTjNIUDBPUDNJK2ZyeDZjWWxpYz0KQWxsb3dlZElQcyA9IDE5Mi4xNjguNTEuMi8zMgo=
