---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resilio-config-v1
  namespace: sync
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
