---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: resilio-sync
  namespace: sync
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: resilio-sync
      version: 5.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/linuxserver/resilio-sync
      tag: version-2.7.2.1375
    env:
      TZ: "Asia/Shanghai"
      PUID: "1000"
      PGID: "1000"
    # podSecurityContext:
    #   runAsUser: 1000
    #   runAsGroup: 1000
    #   fsGroup: 1000
    service:
      main:
        ports:
          http:
            port: 8888
      resilio:
        enabled: true
        type: LoadBalancer
        externalIPs:
          - "${SVC_RESILIO_ADDR}"
        ports:
          resilio:
            enabled: true
            port: 8888
            protocol: TCP
            targetPort: 8888
          bt-tcp:
            enabled: true
            port: 55555
            protocol: TCP
            targetPort: 55555
          bt-udp:
            enabled: true
            port: 55555
            protocol: UDP
            targetPort: 55555
        externalTrafficPolicy: Local
    persistence:
      config:
        enabled: true
        mountPath: /config
        existingClaim: resilio-config-v1

      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NAS_ADDR}"
            path: /tank/Media
        mountPath: /media

      downloads:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NAS_ADDR}"
            path: /tank/Downloads
        mountPath: /downloads

      sync:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NAS_ADDR}"
            path: /tank/Sync
        mountPath: /sync
