---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: syncthing
  namespace: sync
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: syncthing
      version: 3.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: syncthing/syncthing
      tag: 1.18.6
    env:
      TZ: "Asia/Shanghai"
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    service:
      main:
        ports:
          http:
            port: 8384
      web:
        enabled: true
        type: LoadBalancer
        externalIPs:
          - "${SVC_SYNCTHING_ADDR}"
        ports:
          web:
            enabled: true
            port: 8384
            protocol: TCP
            targetPort: 8384
      listen:
        enabled: true
        type: NodePort
        externalTrafficPolicy: Local
        ports:
          listen:
            enabled: true
            port: 22000
            protocol: TCP
            targetPort: 22000
      discovery:
        enabled: true
        type: NodePort
        externalTrafficPolicy: Local
        ports:
          discovery:
            enabled: true
            port: 21027
            protocol: UDP
            targetPort: 21027
            externalTrafficPolicy: Local
    persistence:
      data:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NAS_ADDR}"
            path: /tank/Syncthing
        mountPath: /var/syncthing
